### ISSUE TITLE
Is it for MAC only?

### ISSUE THREAD

**Issue by jarogames** [tuxu/ipynb-quicklook#1]
Is it for MAC only? Or also linux?

**Comment by tuxu** [comment]
Sorry, Quick Look is available on macOS only. On Linux, you might be lucky with the [command line tool](https://github.com/kokes/nbviewer.js/tree/master/cmd) bundled with nbviewer.js and associating it with `ipynb` files.

**Comment by jarogames** [comment]
thanks
