### ISSUE TITLE
Latex code in quicklook

### ISSUE THREAD

**Issue by ferencszalma** [tuxu/ipynb-quicklook#2]
Would it be possible to add MathJax to the code so that Latex equations appear instead of the $...$ in the quicklook view? Or something more difficult is needed to add Latex support? It is just a question. Thanks.

**Comment by tuxu** [comment]
This seems to be a bit more involved, unfortunately. There is an open issue for LaTeX support in nbviewer.js: kokes/nbviewer.js#1. The LaTeX math must be passed down from the Markdown parser to MathJax or similar. Parsing of the $$ and $ delimiters should also match the implementation in Jupyter Notebook...
