### ISSUE TITLE
README.md enhancement

### ISSUE THREAD

**Issue by sy2002** [tuxu/ipynb-quicklook#4]
### Idea for enhancing the documentation in README.md:

You might want to mention in https://github.com/tuxu/ipynb-quicklook#getting-started that if the user copies to his local ~/Library/QuickLook/ instead of the global folder /Library/QuickLook, that then nothing will work.

I stumbled over this, as I normally prefer to install in my local user's folder.

**Comment by tuxu** [comment]
Thanks! You are definitely right, this should be mentioned. If you want to avoid the global installation, you can just use [nbviewer-app](https://github.com/tuxu/nbviewer-app), which ships with the QuickLook generator and should work out of the box.
