### ISSUE TITLE
fails to load in Monterey

### ISSUE THREAD

**Issue by moffat** [tuxu/ipynb-quicklook#9]
Hi,

I've tried installing ipynb-quicklook using both the releases here and homebrew. It doesn't seem to work even after using `qlmanage -r' and 'killlall Finder'. 

Trying from the terminal, I get:

```bash

qlmanage -t LTER_Storminess.ipynb 
Testing Quick Look thumbnails with files:
	LTER_Storminess.ipynb
2022-02-12 10:36:25.187 qlmanage[45324:6583915] *** CFMessagePort: bootstrap_register(): failed 1100 (0x44c) 'Permission denied', port = 0x9003, name = 'com.apple.tsm.portname'
See /usr/include/servers/bootstrap_defs.h for the error codes.

```

any ideas?

**Comment by tuxu** [comment]
Weird. I got the same error messages from the command line (also with `-p` for preview).

Can you try with [nbviewer-app](https://github.com/tuxu/nbviewer-app) (`brew install jupyter-notebook-viewer`) instead? It bundles the Quick Look generator and works out of the box for me on Monterey 12.2. Opening the app once should register the plug-in with Quick Look.

**Comment by moffat** [comment]
I actually solved this by following the instructions in this [stack exchange answer](https://apple.stackexchange.com/questions/7799/quicklook-for-files-with-no-extension-or-an-unknown-extension#comment575250_411423). The error above isn't what's making the plugin fail. Once I added the right `kMDItemContentType` to the Info.plist of your plugin, it works fine. 

Thank you for your work!
